### ISSUE TITLE
Return critical error upon 404 response

### ISSUE THREAD

**Issue by tullis** [phrawzty/check_http_json#28]
Hi,

It would be useful for us if the check could return a critical error if the URL responds with a 404.
At the moment it's returning a warning and I can't see a way to make it critical from the available options.

Thanks.

**Comment by phrawzty** [comment]
Hi @tullis,

This is a fine idea. It would be straightforward enough to add this condition, but I'm not sure I like the idea of doing so unilaterally as it would break the established behaviour for everyone that uses this plugin. How about an option that allows you to specify a list of status codes and their associated Nagios level?  Something like `--status_code <code:level>[,code:level]` for example. That way anybody could assign exits of `[0-4]` for any given HTTP code that was returned. That work for you?

**Comment by tullis** [comment]
Yes thanks.
That would be great.

**Comment by phrawzty** [comment]
Commit 4429465 should satisfy this issue. Give it a spin and let me know - thanks! :smile:

**Comment by phrawzty** [comment]
Hi @tullis - have you had a chance to try the [status_opt](https://github.com/phrawzty/check_http_json/tree/status_opt) branch yet?

**Comment by tullis** [comment]
Hi there,
Not yet, I'm afraid. I'll try to do it early next week and let you know how it goes.
Many thanks again.
-- 
Sent from my blinking phone.

**Comment by phrawzty** [comment]
Hi @tullis - do you have any feedback on this branch?

**Comment by tullis** [comment]
Hi @phrawzty - Many apologies for the long delay.
Thanks ever so much. This now does exactly what I need it to do.
I'm intending to use it to check the status of applications running on [Marathon](http://mesosphere.github.io/marathon/), amongst other things. I'm afraid that there was a delay at our end in rolling out the changes, so the monitoring was similarly delayed.

**Comment by phrawzty** [comment]
Great, I'm glad to hear that it works for you. If you could be so kind as to add your use-case to the [wiki](https://github.com/phrawzty/check_http_json/wiki) (so that others may benefit), that'd be great.

**Comment by tullis** [comment]
I've create a wiki page [here](https://github.com/phrawzty/check_http_json/wiki/Marathon-tasks-example)
Many thanks again.
