### ISSUE TITLE
Is there a way to check multiple values?

### ISSUE THREAD

**Issue by phrawzty** [phrawzty/check_http_json#32]
from @mimmus:

```
I have:

{
"units": [
{
"id": "service1",
"health": 0,
},
{
"id": "service2",
"health": 0,
},
....
{
"id": "serviceN",
"health": 0,
}
]
}

What's the best way to check that ALL health keys are equal to 0?
```

**Comment by phrawzty** [comment]
There's no support for that particular operation in this script.  Basically this is designed to target a single key and analyse the result, and there's no logic for maintaining arbitrary datasets in memory.

If this feature is useful to you, feel free to submit a PR. 😄  Otherwise I'll add it to my TODO for the future.

**Comment by mimmus** [comment]
I have no Ruby skills to create a PR, sorry!

**Comment by simpleuser99** [comment]
check multiple values it sound good. I need it

**Comment by Project0** [comment]
i think it would be great if we can use the option --element_regex for multiple elements to check?

**Comment by Project0** [comment]
With my PR the above example should work like this:
> ./check_http_json.rb -f test.json -E 'units\.\d+\.health' -r '0'  --element_regex_global -v
```
+ Found units\.\d+\.health as units.0.health
+ Found units\.\d+\.health as units.1.health
+ The value of units.0.health is 0
+ The value of units.1.health is 10
CRIT: units.1.health is 10
```

**Comment by phrawzty** [comment]
Thanks for your interest, @Project0!  With reference to #33, I've added lots of comments, and am happy to get a dialogue going on this issue.
