### ISSUE TITLE
Performance Counters

### ISSUE THREAD

**Issue by 3Chris** [phrawzty/check_http_json#38]
Hello,

firstly: Thank you phrawzty for your great script!

Unfortunately I am not able to retrieve the performance values I need.

This is working:
```
check_http_json.rb -u 'http://x/jolokia/read/jboss.as:subsystem=datasources,data-source=*,statistics=pool/ActiveCount' -E '^ActiveCount' -w 5 -c 10 --element_regex_global -p request.type
OK: All 'ActiveCount' (regex) within treshold W:5 C:10 | request.type=read
```

But this do not give any performance values:
```
check_http_json.rb -u 'http://x/jolokia/read/jboss.as:subsystem=datasources,data-source=*,statistics=pool/ActiveCount' -E '^ActiveCount' -w 5 -c 10 --element_regex_global -p value.jboss.as:data-source=product1,statistics=pool,subsystem=datasources.ActiveCount
OK: All 'ActiveCount' (regex) within treshold W:5 C:10 |
```

this is my json:
```
{
  "timestamp": 1515660256,
  "status": 200,
  "request": {
    "mbean": "jboss.as:data-source=*,statistics=pool,subsystem=datasources",
    "attribute": "ActiveCount",
    "type": "read"
  },
  "value": {
    "jboss.as:data-source=product1,statistics=pool,subsystem=datasources": {
      "ActiveCount": 0
    },
    "jboss.as:data-source=product2,statistics=pool,subsystem=datasources": {
      "ActiveCount": 0
    },
    "jboss.as:data-source=product3,statistics=pool,subsystem=datasources": {
      "ActiveCount": 0
    }
  }
}
```

**Comment by phrawzty** [comment]
> firstly: Thank you phrawzty for your great script!

You're welcome!

> But this do not give any performance values:
> `-p value.jboss.as:data-source=product1,statistics=pool,subsystem=datasources.ActiveCount`

Performance metrics are comma-separated. That string contains two commas, therefore you're specifying three different keys (instead of the one you intended). To be honest, this is not a use-case that I anticipated, and I have no immediate solution for you. 😢 

I'll play around with some things and get back to you.

**Comment by 3Chris** [comment]
Oh, I failed to see that... Thank's for your help and fast response!

It would be also very nice, if there would be the possibility to do something like that:
-p value.jboss.as:data-source=*,statistics=pool,subsystem=datasources.ActiveCount
instead of
-p value.jboss.as:data-source=product1,statistics=pool,subsystem=datasources.ActiveCount

To get ActiveCounts for all data-sources :+1:

**Comment by phrawzty** [comment]
Ok, I added some code to allow for alternative character to use to separate the performance items. Consider your JSON and example:
```
$ ./check_http_json.rb -f ~/38.json -E 'ActiveCount' -w 5 -c 10 --element_regex_global -p value§jboss.as:data-source=product1,statistics=pool,subsystem=datasources§ActiveCount -d § --perf_splitter=±

OK: All 'ActiveCount' (regex) within treshold W:5 C:10 | value§jboss.as:data-source=product1,statistics=pool,subsystem=datasources§ActiveCount=0
```

I set the key delimiter to `§` (to avoid the periods from being interpreted), and added an option `--perf_splitter` to specify the character (`±`) to split items in the performance key array. Does that output match what you expect?

**Comment by 3Chris** [comment]
You already published your changes? As I am not able to see the new code.

However, it looks awesome, but is it also possible to get all ActiveCounters (product1, product2, product3, etc.) in one query? By using wildcard or regex?

**Comment by phrawzty** [comment]
> You already published your changes? As I am not able to see the new code.

Github was having issues yesterday. I have pushed a [branch](https://github.com/phrawzty/check_http_json/tree/38) with the code for you to test.

**Comment by 3Chris** [comment]
It is working :+1: 

Thank you for help :-)
