### ISSUE TITLE
feature request: performance data

### ISSUE THREAD

**Issue by loeken** [phrawzty/check_http_json#44]
First of thanks for this plugin, super useful to me, there is one little thing that would improve my config of this plugin a lot as im monitoring larger arrays with a lot of subarrays.

let's say i have a simple array

{
	"Main": {
		"Sub1": 1,
		"Sub2": 2
        }
}

at the moment i would have to specify Main.Sub1,Main.Sub2 to get all "Sub" elements. this is okey for small arrays for bigger arrays it would be easier to simply specifiy -p Main ( and then get all Sub elements automatically ) or maybe even a -p Main.* to get all of them.

I don't know ruby at all but i think this could easily be achived with some small if around https://github.com/phrawzty/check_http_json/blob/8e137819d5818f7c8da8337f2f096ef5814dc8fe/check_http_json.rb#L473 here

keep up the good work!

**Comment by phrawzty** [comment]
Hello,

I haven't used Nagios in a long time, nor have I really touched this code recently, so to be honest I'm not inclined to make any major modifications to the functionality at this time.

As always, pull requests are welcome. :)
