### ISSUE TITLE
warning when running on windows host

### ISSUE THREAD

**Issue by cullenp** [phrawzty/check_http_json#46]
Windows: Windows Server 2008 R2
ruby: 2.7.1
check_http_json from the master branch 

C:\Program Files\NSClient++\scripts>check_http_json.rb -u http://localhost:1701/
status -E CpuUsage -w 40 -c 100 -p CpuUsage
C:/Program Files/NSClient++/scripts/check_http_json.rb:605: warning: deprecated
Object#=~ is called on Float; it always returns nil
OK: First 'CpuUsage' (regex) within treshold W:40 C:100 | CpuUsage=14.0619164304
68136

**Comment by cullenp** [comment]
We ended up commenting out the code at line 605-609 and then it no longer registered an error and produced the values and perf data we required.

`    #if element_value =~ /\D/
    #    say(options[:v], 'The value of %s contains non-numeric characters.' % [element])
    #    Nagios.unknown = 'Return value syntax failure.'
    #    next
    #end`

**Comment by phrawzty** [comment]
@cullenp weird! I'm glad that you found a solution to your problem. I don't have a Windows machine to test on, unfortunately.
